variable "aws_region" { type = string }
//variable "aws_profile" { type = string }
variable "aws_account_id" { type = string }
variable "vpc_cidr" { type = string }
variable "key-pair-name" { type = string }
variable "rsa-bits" { type = number }
variable "bastion_instance_type" { type = string }
variable "bastion-root-vol-size" { type = number }
variable "bastion-vol-type" { type = string }
variable "byte_length" { type = number }
variable "db_instance_type" { type = string }
variable "db_engine_version" { type = string }
variable "db_engine_mode" { type = string }
variable "secrets_rotation_interval" { type = number }
//variable "PUBLIC_KEY" { type = string }
//variable "db_subnet_count" {type = number}
//variable "db_allocated_storage" {type = number}
//variable "role_arn" { type = string }
//variable "session_name" { type = string }
//variable "az_count" { type = number }
